"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class marker_t(object):
    __slots__ = ["visible", "position"]

    def __init__(self):
        self.visible = 0
        self.position = [ 0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(marker_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.visible))
        buf.write(struct.pack('>3i', *self.position[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != marker_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return marker_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = marker_t()
        self.visible = struct.unpack(">b", buf.read(1))[0]
        self.position = struct.unpack('>3i', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if marker_t in parents: return 0
        tmphash = (0xc60a1b7d7f663317) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if marker_t._packed_fingerprint is None:
            marker_t._packed_fingerprint = struct.pack(">Q", marker_t._get_hash_recursive([]))
        return marker_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

